[tool.black]
line-length = 125
target-version = ['py38']

[tool.isort]
profile = "black"
known_first_party = "rancher_gitlab_deploy"
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
line_length = 125
multi_line_output = 3
force_single_line = "true"
